spring:
  application:
      name: gateway
  slueth:
      sampler:
        probability: 1.0
server:
    port: 8090
zuul:
  routes:
    greetingRoute:
      path: /sayHello
      serviceId: greetings
    greetingConsumerRoute:
      path: /gclient/sayHelloo
      serviceId: greetingsConsumer

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.0.108:8761/eureka/